### ISSUE TITLE
crashes when extra utilities is present

### ISSUE THREAD

**Issue by matthewray11** [Ex-Astris-Rebirth/Ex-Astris-Rebirth#42]
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 6/9/15 3:00 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/rwtema/extrautils/item/ItemHeatingCoil
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:535)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:242)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: com/rwtema/extrautils/item/ItemHeatingCoil
	at com.rwtema.extrautils.ExtraUtilsMod.preInit(ExtraUtilsMod.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:533)
	... 10 more
Caused by: java.lang.ClassNotFoundException: com.rwtema.extrautils.item.ItemHeatingCoil
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more
Caused by: java.lang.NoClassDefFoundError: cofh/api/energy/ItemEnergyContainer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 39 more
Caused by: java.lang.ClassNotFoundException: cofh.api.energy.ItemEnergyContainer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 183272384 bytes (174 MB) / 794296320 bytes (757 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.3.1408 66 mods loaded, 65 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.3.1408-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.3.1408} [Minecraft Forge] (forge-1.7.10-10.13.3.1408-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	CodeChickenCore{1.0.6.44} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	NotEnoughItems{1.0.4.107} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.107-universal.jar) Unloaded->Constructed->Pre-initialized
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	battlegear2{1.0.7.0} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.7.0.jar) Unloaded->Constructed->Pre-initialized
	jammyfurniture{4.6} [Jammy Furniture Mod] (1.7.10_Jammy_Furniture_Mod_V4.6_RC1.jar) Unloaded->Constructed->Pre-initialized
	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar) Unloaded->Constructed->Pre-initialized
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized
	adventurebackpack{0.7.4b} [Adventure Backpack] (adventurebackpack-1.7.10-0.7.4b.jar) Unloaded->Constructed->Pre-initialized
	asielib{0.2.7} [asielib] (AsieLib-1.7.10-0.2.7.jar) Unloaded->Constructed->Pre-initialized
	hud{1.1a} [Better HUD] (Better HUD by NukeDuck [1.7.10][1.1a].zip) Unloaded->Constructed->Pre-initialized
	betterstorage{0.13.1.126} [BetterStorage] (BetterStorage-1.7.10-0.13.1.126.jar) Unloaded->Constructed->Pre-initialized
	BiblioCraft{1.9.1} [BiblioCraft] (BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
	Botania{r1.4-159} [Botania] (Botania r1.4-159.jar) Unloaded->Constructed->Pre-initialized
	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized
	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized
	craftguide{1.6.8.1} [CraftGuide] (CraftGuide-Mod-1.7.10.zip) Unloaded->Constructed->Pre-initialized
	customnpcs{1.7.10b} [CustomNpcs] (Custom-NPCs-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	props{2.0.2} [Decocraft] (Decocraft-2.0.2_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7.jar) Unloaded->Constructed->Pre-initialized
	DynamicTransport{0.1.2.0} [Dynamic Transport] (DynamicTransport-0.1.2.0.jar) Unloaded->Constructed->Pre-initialized
	exnihilo{1.37} [Ex Nihilo] (Ex-Nihilo-1.37.jar) Unloaded->Constructed->Pre-initialized
	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed->Pre-initialized
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized
	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized
	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80 (1).jar) Unloaded->Constructed->Pre-initialized
	exastrisrebirth{MC1.7.10-1.01-42} [Ex Astris Rebirth] (Ex-Astris-Rebirth-MC1.7.10-1.01-42.jar) Unloaded->Constructed->Pre-initialized
	ExtraUtilities{1.2.4b} [Extra Utilities] (extrautilities-1.2.4b.jar) Unloaded->Constructed->Errored
	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized
	harvestcraft{1.7.10d} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10f.jar) Unloaded->Constructed->Pre-initialized
	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) Unloaded->Constructed->Pre-initialized
	fastleafdecay{1.0} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized
	flowercraftmod{1.9} [Flowercraft] (Flowercraftmod 1.8 - 1.7.10 Forge.jar) Unloaded->Constructed->Pre-initialized
	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) Unloaded->Constructed->Pre-initialized
	GraviGun{4.0.0-beta} [GraviGun] (GravityGun-4.0.0-beta.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft{2.1.0a} [Growthcraft] (growthcraft-core-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar] (growthcraft-cellar-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Apples{2.1.0} [Growthcraft Apples] (growthcraft-apples-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo] (growthcraft-bamboo-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Bees{2.1.0} [Growthcraft Bees] (growthcraft-bees-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap] (growthcraft-fishtrap-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Grapes{2.1.0} [Growthcraft Grapes] (growthcraft-grapes-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Hops{2.1.0} [Growthcraft Hops] (growthcraft-hops-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Rice{2.1.0a} [Growthcraft Rice] (growthcraft-rice-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (Inventory-Tweaks-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	radixcore{1.3.4} [RadixCore] (RadixCore-1.7.10-1.3.4-universal.jar) Unloaded->Constructed->Pre-initialized
	mca{4.1.1} [Minecraft Comes Alive] (MCA-4.1.1 MC-1.7.10.zip) Unloaded->Constructed->Pre-initialized
	MoarFood{V5.5.0} [MoarFood] (MoarFood-5.5.0.jar) Unloaded->Constructed->Pre-initialized
	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-268.jar) Unloaded->Constructed->Pre-initialized
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-512.jar) Unloaded->Constructed->Pre-initialized
	weeeflowers{1.7.2b} [Pam's Weee! Flowers] (Pams-Weee-Flowers-Mod-1.7.10.zip) Unloaded->Constructed->Pre-initialized
	TeNNoX_Planetoid{0.9.9.1} [Planetoid] (Planetoid-1.7.10-0.9.9.1.jar) Unloaded->Constructed->Pre-initialized
	plantmegapack{4.02} [Plant Mega Pack] (Plant-Mega-Pack-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	PortalGun{4.0.0-beta-4} [PortalGun] (PortalGun-4.0.0-beta-4.jar) Unloaded->Constructed->Pre-initialized
	primitivemobs{1.0} [Primitive Mobs] (primitivemobs-1.0c-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	rafradek_wallpaint{1.5.4} [Wall Painter] (rafradek_wallpaint-1.5.4.jar) Unloaded->Constructed->Pre-initialized
	statues{2.1.3} [Statues] (statues-1.7.10-2.1.3.jar) Unloaded->Constructed->Pre-initialized
	TiCTooltips{1.2.4} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized
	TMechworks{1.7.10-67.34d1d9b} [Tinkers' Mechworks] (TMechworks_mc1.7.10_0.2.8.jar) Unloaded->Constructed->Pre-initialized
	treeGrowingSimulator{0.0.3} [Tree Growing Simulator 2014] (TreeGrowingSimulator2014-MC1.7.10-0.0.3-22.jar) Unloaded->Constructed->Pre-initialized
	wawla{1.2.1} [What Are We Looking At] (Wawla-1.2.1_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	asielibcore{} [AsieLib CoreMod] (minecraft.jar) Unloaded->Disabled
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.3.11672 Compatibility Profile Context' Renderer: 'ATI Radeon HD 4250'
	OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8

**Comment by LoveHoly** [comment]
Need Ex Nihilo version update

latest version download here : http://www.curse.com/mc-mods/minecraft/221696-ex-nihilo#t1:other-downloads
