### ISSUE TITLE
Crash on launch, NoClassDefFound

### ISSUE THREAD

**Issue by TheFireRodan** [Ex-Astris-Rebirth/Ex-Astris-Rebirth#60]
[spoiler]Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: tconstruct/library/weaponry/ProjectileWeapon
 at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
 at cpw.mods.fml.common.Loader.loadMods(Loader.java:502)
 at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:215)
 at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
 at net.minecraft.client.main.Main.main(SourceFile:148)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: tconstruct/library/weaponry/ProjectileWeapon
 at java.lang.Class.forName0(Native Method)
 at java.lang.Class.forName(Unknown Source)
 at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:42)
 at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:510)
 at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
 at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
 at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
 at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
 at com.google.common.eventbus.EventBus.post(EventBus.java:275)
 at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
 at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
 at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
 at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
 at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
 at com.google.common.eventbus.EventBus.post(EventBus.java:275)
 at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
 at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
 ... 10 more
Caused by: java.lang.ClassNotFoundException: tconstruct.library.weaponry.ProjectileWeapon
 at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
 at java.lang.ClassLoader.loadClass(Unknown Source)
 at java.lang.ClassLoader.loadClass(Unknown Source)
 ... 35 more
Caused by: java.lang.NoClassDefFoundError: tconstruct/library/tools/ToolCore
 at java.lang.ClassLoader.defineClass1(Native Method)
 at java.lang.ClassLoader.defineClass(Unknown Source)
 at java.security.SecureClassLoader.defineClass(Unknown Source)
 at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
 ... 37 more
Caused by: java.lang.ClassNotFoundException: tconstruct.library.tools.ToolCore
 at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
 at java.lang.ClassLoader.loadClass(Unknown Source)
 at java.lang.ClassLoader.loadClass(Unknown Source)
 ... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
 Minecraft Version: 1.7.10
 Operating System: Windows 8.1 (amd64) version 6.3
 Java Version: 1.8.0_45, Oracle Corporation
 Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
 Memory: 279839272 bytes (266 MB) / 824705024 bytes (786 MB) up to 3817865216 bytes (3641 MB)
 Mod Pack: ~~ERROR~~ NullPointerException: null
 LiteLoader Mods: ~~ERROR~~ NullPointerException: null
 LaunchWrapper: 43 active transformer(s)
 - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
 - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
 - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
 - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
 - Transformer: net.minecraftforge.classloading.FluidIdTransformer
 - Transformer: am2.preloader.BytecodeTransformers
 - Transformer: mods.betterfoliage.loader.impl.BetterFoliageTransformer
 - Transformer: codechicken.lib.asm.ClassHeirachyManager
 - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
 - Transformer: codechicken.core.asm.TweakTransformer
 - Transformer: codechicken.core.asm.DelegatedTransformer
 - Transformer: codechicken.core.asm.DefaultImplementationTransformer
 - Transformer: mrtjp.relocation.asm.Transformer
 - Transformer: invtweaks.forge.asm.ContainerTransformer
 - Transformer: com.creativemd.itemphysic.ItemTransformer
 - Transformer: codechicken.nei.asm.NEITransformer
 - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
 - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
 - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
 - Transformer: me.guichaguri.betterfps.transformers.MathTransformer
 - Transformer: me.guichaguri.betterfps.transformers.EventTransformer
 - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
 - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
 - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
 - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
 - Transformer: invtweaks.forge.asm.ITAccessTransformer
 - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
 - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
 - Transformer: com.olafski.fastleafdecay.FldTransformer
 - Transformer: com.gildedgames.util.threadedlighting.asm.TLTransformer
 - Transformer: de.sanandrew.core.manpack.transformer.TransformBadPotionsATN
 - Transformer: de.sanandrew.core.manpack.transformer.TransformEntityThrowable
 - Transformer: de.sanandrew.core.manpack.transformer.TransformELBAttackingPlayer
 - Transformer: de.sanandrew.core.manpack.transformer.TransformPlayerDismountCtrl
 - Transformer: de.sanandrew.core.manpack.transformer.TransformHorseArmor
 - Transformer: de.sanandrew.core.manpack.transformer.TransformEnderman
 - Transformer: cuchaz.ships.core.CoreModTransformer
 - Transformer: shadersmodcore.transform.SMCClassTransformer
 - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
 - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
 - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
 - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
 - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
 JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:MaxPermSize=2G
 AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
 IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
 FML: MCP v9.05 FML v7.10.114.1388 Minecraft Forge 10.13.3.1388 76 mods loaded, 76 mods active
 mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
 FML{7.10.114.1388} [Forge Mod Loader] (forge-1.7.10-10.13.3.1388-1.7.10.jar) Unloaded->Constructed
 Forge{10.13.3.1388} [Minecraft Forge] (forge-1.7.10-10.13.3.1388-1.7.10.jar) Unloaded->Constructed
 AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) Unloaded->Constructed
 CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed
 itemphysic{1.1.5} [ItemPhysic] (minecraft.jar) Unloaded->Constructed
 NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) Unloaded->Constructed
 mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) Unloaded->Constructed
 sapmanpack{2.5.1} [SanAndreasPs Manager Pack CORE edition] (SAPManPack-1.7.10-2.5.1.jar) Unloaded->Constructed
 cuchaz.ships.core{1.7.10-1.0.3} [Ships Mod Core] (minecraft.jar) Unloaded->Constructed
 gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (gilded-games-util.jar) Unloaded->Constructed
 dynamicswordskills{1.7.10-1.6.5} [Dynamic Sword Skills] (1.7.10-dynamicswordskills-1.6.5.jar) Unloaded->Constructed
 AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed
 arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) Unloaded->Constructed
 aether{Alpha 1.7.10-1.4} [Aether II] (aether.jar) Unloaded->Constructed
 AgriCraft{1.7.10-1.4.0-beta-1} [AgriCraft] (AgriCraft-1.7.10-1.4.0-beta-1-1.7.10.jar) Unloaded->Constructed
 Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed
 BetterFoliage{1.0.13} [Better Foliage] (BetterFoliage-mc1.7-1.0.13.jar) Unloaded->Constructed
 BiblioCraft{1.10.5} [BiblioCraft] (BiblioCraft[v1.10.6][MC1.7.10].jar) Unloaded->Constructed
 ExtrabiomesXL{3.16.2} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.2.jar) Unloaded->Constructed
 BiblioWoodsEBXL{1.4} [BiblioWoods ExtraBiomesXL Edition] (BiblioWoods[ExtraBiomesXL][v1.4].jar) Unloaded->Constructed
 Botania{r1.7-208} [Botania] (Botania r1.7-208.jar) Unloaded->Constructed
 CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) Unloaded->Constructed
 ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) Unloaded->Constructed
 ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) Unloaded->Constructed
 chisel{2.3.10.37} [Chisel 2] (Chisel2-2.3.10.37.jar) Unloaded->Constructed
 claysoldiers{2.0.0-beta.2} [Clay Soldiers Mod] (ClaySoldiersMod-1.7.10-2.0.0-beta.2.jar) Unloaded->Constructed
 ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) Unloaded->Constructed
 creativecore{1.2.0} [CreativeCore] (CreativeCore v1.2.2 mc1.7.10.jar) Unloaded->Constructed
 exnihilo{1.38-45} [Ex Nihilo] (Ex-Nihilo-1.38-45.jar) Unloaded->Constructed
 MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed
 Mantle{1.7.10-0.3.2.jenkins188} [Mantle] (Mantle-1.7.10-0.3.2a.jar) Unloaded->Constructed
 TConstruct{1.7.10-1.8.6b.build976} [Tinkers' Construct] (TConstruct-1.7.10-1.8.6b.jar) Unloaded->Errored
 Metallurgy{4.0.8} [Metallurgy 4] (Metallurgy-1.7.10-4.0.8.97.jar) Unloaded->Constructed
 exastrisrebirth{MC1.7.10-1.01-45} [Ex Astris Rebirth] (Ex-Astris-Rebirth-MC1.7.10-1.01-45.jar) Unloaded->Constructed
 ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) Unloaded->Errored
 fastleafdecay{1.1} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.1.jar) Unloaded->Constructed
 FWG{1.0.3} [Fun World Gen] (FWG-1.0.3.jar) Unloaded->Constructed
 GraveStone{2.12.3} [GraveStone] (GraveStone-2.12.4.jar) Unloaded->Constructed
 inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed
 JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) Unloaded->Constructed
 RadixCore{2.0.2} [RadixCore] (RadixCore-1.7.10-2.0.2-universal.jar) Unloaded->Constructed
 MCA{1.7.10-5.0.7.2} [Minecraft Comes Alive] (MCA-1.7.10-5.0.7.2-universal.jar) Unloaded->Constructed
 millenaire{6.0.0} [Millénaire] (millenaire-6.0.0.jar) Unloaded->Constructed
 NEIAddons{1.12.11.36} [NEI Addons] (neiaddons-1.12.11.36-mc1.7.10.jar) Unloaded->Constructed
 NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools] (neiaddons-1.12.11.36-mc1.7.10.jar) Unloaded->Constructed
 NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.11.36-mc1.7.10.jar) Unloaded->Constructed
 NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany] (neiaddons-1.12.11.36-mc1.7.10.jar) Unloaded->Constructed
 NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry] (neiaddons-1.12.11.36-mc1.7.10.jar) Unloaded->Constructed
 NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables] (neiaddons-1.12.11.36-mc1.7.10.jar) Unloaded->Constructed
 NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo] (neiaddons-1.12.11.36-mc1.7.10.jar) Unloaded->Constructed
 primitivemobs{1.0} [Primitive Mobs] (primitivemobs-1.0c-1.7.10.jar) Unloaded->Constructed
 ProjectE{1.7.10-PE1.8.0} [ProjectE] (ProjectE-1.7.10-PE1.8.0.jar) Unloaded->Constructed
 MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.1.0.31-universal.jar) Unloaded->Constructed
 ProjRed|Core{4.7.0pre8.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre8.92-Base.jar) Unloaded->Constructed
 ProjRed|Transmission{4.7.0pre8.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar) Unloaded->Constructed
 ProjRed|Transportation{4.7.0pre8.92} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre8.92-Mechanical.jar) Unloaded->Constructed
 ProjRed|Compatibility{4.7.0pre8.92} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre8.92-Compat.jar) Unloaded->Constructed
 ProjRed|Integration{4.7.0pre8.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar) Unloaded->Constructed
 ProjRed|Fabrication{4.7.0pre8.92} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre8.92-Fabrication.jar) Unloaded->Constructed
 ProjRed|Illumination{4.7.0pre8.92} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre8.92-Lighting.jar) Unloaded->Constructed
 ProjRed|Expansion{4.7.0pre8.92} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre8.92-Mechanical.jar) Unloaded->Constructed
 RWG{Alpha 1.3.2} [Realistic World Gen Alpha] (RWG-alpha-1.3.2.jar) Unloaded->Constructed
 cuchaz.cuchazinteractive{1.7.10-1.0} [Cuchaz Interactive] (shipsMod-v1.7.10-1.0.3.jar) Unloaded->Constructed
 cuchaz.ships{1.7.10-1.0.3} [Ships Mod] (shipsMod-v1.7.10-1.0.3.jar) Unloaded->Constructed
 Slugs Magic Resistance Mod{0.9} [Slug's Magic Resistance Mod] (Slugs Damage Tweaks-0.9.jar) Unloaded->Constructed
 SpecialMobs{3.1.1} [Special Mobs] (SpecialMobs-1.7.10-3.1.1.jar) Unloaded->Constructed
 TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) Unloaded->Errored
 TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) Unloaded->Errored
 worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) Unloaded->Constructed
 McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) Unloaded->Constructed
 ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) Unloaded->Constructed
 MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) Unloaded->Constructed
 RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) Unloaded->Constructed
 IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) Unloaded->Errored
 ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) Unloaded->Constructed
 Mantle Environment: Environment healthy.
 TConstruct Environment: Environment healthy.[/spoiler]
[p]//Crash Log.[/p]

[p]Everything downloaded new yesterday.[/p]
[p]Forge 1388.[/p]
[p]Mods from the list being used:[/p]

[p][b]ArsMagica[/b][/p]
[p][s]BigReactors[/s][/p]
[p][s]BloodMagic[/s][/p]
[p][b]Botania[/b][/p]
[p][b]Chisel2 (not chisel1)[/b][/p]
[p][s]DraconicEvolution[/s][/p]
[p][s]EnderIO[/s][/p]
[p][s]FoodPlus[/s][/p]
[p][b]Metallurgy[/b][/p]
[p][s]MineFactoryReloaded[/s][/p]
[p][s]Natura[/s][/p]
[p][s]RedstoneArsnal[/s][/p]
[p][s]RotaryCraft[/s][/p]
[p][b]TConstruct[/b][/p]
[p][s]Thaumcraft[/s][/p]
[p][s]ThermalExpansion[/s][/p]
[p][s]TSteelworks[/s][/p]
[p][s]Witchery[/s][/p]
[p][s]Biomes O' Plenty[/s][/p]

[p]Also, if BoP is in, I'd recommend taking out EBXL next, as they're similar mods.[/p]

**Comment by MikeLydeamore** [comment]
I am unable to reproduce this crash. Can you try updating your Tinkers version?

**Comment by ghost** [comment]
It IS updated. 1.8.7, no?

**Comment by ghost** [comment]
All of my mods are updated every few days, yesterday including.
