### ISSUE TITLE
Crash when put block in automatic sieve ( sand, gravel,...)

### ISSUE THREAD

**Issue by vietduckg10** [Ex-Astris-Rebirth/Ex-Astris-Rebirth#76]
there is my crash report
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 9/11/16 5:34 PM
Description: Ticking block entity

java.lang.NoClassDefFoundError: cofh/lib/util/helpers/ItemHelper
    at kr.loveholy.exastrisrebirth.tileentity.TileEntitySieveAutomatic.ProcessContents(TileEntitySieveAutomatic.java:160)
    at kr.loveholy.exastrisrebirth.tileentity.TileEntitySieveAutomatic.func_145845_h(TileEntitySieveAutomatic.java:116)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: cofh.lib.util.helpers.ItemHelper
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 9 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at kr.loveholy.exastrisrebirth.tileentity.TileEntitySieveAutomatic.ProcessContents(TileEntitySieveAutomatic.java:160)
    at kr.loveholy.exastrisrebirth.tileentity.TileEntitySieveAutomatic.func_145845_h(TileEntitySieveAutomatic.java:116)

-- Block entity being ticked --
Details:
    Name: exastrisrebirth.blockSieveAutomatic // kr.loveholy.exastrisrebirth.tileentity.TileEntitySieveAutomatic
    Block type: ID #1510 (exastrisrebirth.blockSieveAutomatic // kr.loveholy.exastrisrebirth.block.BlockSieveAutomatic)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-745,63,-108), Chunk: (at 7,3,4 in -47,-7; contains blocks -752,0,-112 to -737,255,-97), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
    Actual block type: ID #1510 (exastrisrebirth.blockSieveAutomatic // kr.loveholy.exastrisrebirth.block.BlockSieveAutomatic)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: New World
    All players: 1 total; [EntityPlayerMP['DUCVN'/23, l='New World', x=-775.93, y=86.50, z=-130.33]]
    Chunk stats: ServerChunkCache: 864 Drop: 0
    Level seed: 4239199425327593737
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-22,64,-28), Chunk: (at 10,4,4 in -2,-2; contains blocks -32,0,-32 to -17,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Level time: 1287247 game time, 1709028 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 66304 (now: false), thunder time: 38735 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 288694040 bytes (275 MB) / 797949952 bytes (760 MB) up to 2134114304 bytes (2035 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 42 mods loaded, 42 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.120} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
    UCHIJAAAA   ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCHIJAAAA   abyssalcraft{1.9.1.3} [AbyssalCraft](AbyssalCraft-1.7.10-1.9.1.3-FINAL.jar) 
    UCHIJAAAA   ActuallyAdditions{1.7.10-r21} [Actually Additions](ActuallyAdditions-1.7.10-r21.jar) 
    UCHIJAAAA   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJAAAA   Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJAAAA   Botania{r1.7-226} [Botania](Botania r1.7-226.jar) 
    UCHIJAAAA   druidry{2016.8.10-1.7.10} [§2Druidry](druidry%282016.8.10.2%29%281.7.10%29.jar) 
    UCHIJAAAA   ForgeMultipart{1.1.2.331} [Forge Multipart](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UCHIJAAAA   Mekanism{9.1.0} [Mekanism](Mekanism-1.7.10-9.1.0.281.jar) 
    UCHIJAAAA   EnderIO{1.7.10-2.2.8.381} [Ender IO](EnderIO-1.7.10-2.2.8.381.jar) 
    UCHIJAAAA   exnihilo{1.38-53} [Ex Nihilo](Ex-Nihilo-1.38-53.jar) 
    UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins188} [Mantle](Mantle-1.7.10-0.3.2a.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAA   TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct](TConstruct-1.7.10-1.8.7.jar) 
    UCHIJAAAA   exastrisrebirth{MC1.7.10-1.01-null} [Ex Astris Rebirth](Ex-Astris-Rebirth-MC1.7.10-1.01-null.jar) 
    UCHIJAAAA   ExtraUtilities{1.1.0k} [Extra Utilities](Extra-Utilities-Mod-1.7.10.jar) 
    UCHIJAAAA   fastleafdecay{1.3} [Fast Leaf Decay](FastLeafDecay-1.7.10-1.3.jar) 
    UCHIJAAAA   inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCHIJAAAA   IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCHIJAAAA   JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    UCHIJAAAA   journeymap{5.1.1b8} [JourneyMap](journeymap-1.7.10-5.1.1b8-unlimited.jar) 
    UCHIJAAAA   MekanismGenerators{9.1.0} [MekanismGenerators](MekanismGenerators-1.7.10-9.1.0.281.jar) 
    UCHIJAAAA   MekanismTools{9.1.0} [MekanismTools](MekanismTools-1.7.10-9.1.0.281.jar) 
    UCHIJAAAA   minechem{5.0.5.406} [Minechem](Minechem-1.7.10-5.0.5.406.jar) 
    UCHIJAAAA   NEIAddons{1.12.15.41} [NEI Addons](neiaddons-1.12.15.41-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Developer{1.12.15.41} [NEI Addons: Developer Tools](neiaddons-1.12.15.41-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|AppEng{1.12.15.41} [NEI Addons: Applied Energistics 2](neiaddons-1.12.15.41-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Botany{1.12.15.41} [NEI Addons: Botany](neiaddons-1.12.15.41-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Forestry{1.12.15.41} [NEI Addons: Forestry](neiaddons-1.12.15.41-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|CraftingTables{1.12.15.41} [NEI Addons: Crafting Tables](neiaddons-1.12.15.41-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|ExNihilo{1.12.15.41} [NEI Addons: Ex Nihilo](neiaddons-1.12.15.41-mc1.7.10.jar) 
    UCHIJAAAA   ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164.jar) 
    UCHIJAAAA   Translocator{1.1.2.15} [Translocator](Translocator-1.7.10-1.1.2.15-universal.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.6} [Waila Harvestability](WailaHarvestability-mc1.7.10-1.1.6.jar) 
    UCHIJAAAA   McMultipart{1.1.2.331} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UCHIJAAAA   IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
    UCHIJAAAA   ForgeMicroblock{1.1.2.331} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['DUCVN'/23, l='New World', x=-775.93, y=86.50, z=-130.33]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Ampflower** [comment]
Try installing CoFH Core or CoFH Lib. This mod will not work without it.
